---
- name: Ensure the local configuration folder exists
  ansible.builtin.file:
    path: ./instructions
    state: directory

- name: Render ssh-config
  ansible.builtin.template:
    src: ssh-config
    dest: ./instructions/ssh-config

- name: Render test script
  ansible.builtin.template:
    src: test-all.sh
    dest: ./instructions/test-all.sh
  vars:
    instances: '{{ instance_groups | map(attribute="name") }}'

- name: Ensure the local per-group configuration folder exists
  ansible.builtin.file:
    path: ./instructions/per-group
    state: directory

- name: Ensure a configuration folder exists for each group
  ansible.builtin.file:
    path: ./instructions/per-group/{{ item.name }}
    state: directory
  loop: "{{ instance_groups }}"

- name: Generate a keypair for each group
  community.crypto.openssh_keypair:
    path: ./instructions/per-group/{{ item.name }}/id_ecdsa
    type: "ecdsa"
    comment: "ubuntu@{{ item.name }}"
  loop: "{{ instance_groups }}"

- name: Render bastion authorized_keys
  ansible.builtin.template:
    src: authorized_keys
    dest: ./instructions/authorized_keys

- name: Render instructions for each group
  ansible.builtin.template:
    src: per-group.md
    dest: ./instructions/per-group/{{ item.name }}/mail.txt
  loop: "{{ instance_groups }}"

- name: Render minio admin script
  ansible.builtin.template:
    src: minio-admin.sh
    dest: ./instructions/minio-admin.sh
  vars:
    instances: '{{ instance_groups | map(attribute="name") }}'
