bastion_host: "185.155.92.52"
cache_dir: "/var/cache/ansible"

docker_bridge_range: "10.{{ host_index + 10 }}.0.0/16"
additional_authorized_keys:
  - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP84fwAsjyX4ziJvQ4HZesaVRbvhQvCEYPfKBNBSCWHsnnDQn4o85HAdKceVwcNN/wlfm+AuH9pNpoJgpEEfpy4= sandhose@Quentins-MacBook-Pro.local"

key_to_remove: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJcxqlq0FxBGncJVoRm+S9MnCmJTuQMsypkifAqL6+Cgqgxi66LGuz3emsUfY4gtpb18vddbBO/CrmlZ1TzKVaxdoUF6c1k2oTUfykZD9Yw9v3CfidRRp7dnyTGV+Teh7uoOgw78jabGw0zirh/5S4E7lpXzPLzjRV2hfwef24hht69RB8vHGYZnb/uyFv23u3raZRNhCzuIwopgnm6cbbQ+gLRGEA6tQ7Alm7PNfcydHjTBWBHlzTlEXJqUotBePp2fDSjIvh6nBy9Ue+B/EqzByeGni37QyyO/KcYSws/KQuRlD/YC0KEHmOGhth4mLbMVxRjVs8YyXxfLUwskSF Generated-by-Nova"

my_groups: "{{ instance_groups | selectattr('members', 'contains', inventory_hostname) }}"
is_main_instance: "{{ host_index == 100 }}"
main_instance_group: "{{ is_main_instance | ternary(my_groups | list | first, []) }}"
