bastion_host: "185.155.93.67"
cache_dir: "/var/cache/ansible"

docker_bridge_range: "10.{{ host_index + 10 }}.0.0/16"
additional_authorized_keys:
  - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP84fwAsjyX4ziJvQ4HZesaVRbvhQvCEYPfKBNBSCWHsnnDQn4o85HAdKceVwcNN/wlfm+AuH9pNpoJgpEEfpy4= sandhose@Quentins-MacBook-Pro.local"

key_to_remove: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLrjTgYow3Ba9tsfm3nSh7XyOP3xM0gbjsf/obB94cbeZs8gUnU0eDEai9fqJDqX+1vBJSHIHEiXbrc6Jydv2cbyJMpP3rEAYTQO/dsKqUPk+HFhJ3ZIU+yID7yCIIGzjZytxf1qAOJmW5j1skmvVioQdGrKFsiqlEqx6SXdmsoa9ue4z75zBAUID/nIyULgwXJzDxW0UWKnUcch6WeNToTL+KCYpNb3sM/VgB+d5Tt2vuxSpPzY6TtSfwjXkElzySwYfC1LR33pJbE92w5XRQNsfmKwk3YgfyHMn9Fv31Kd3z1wp7fLdWIEAbL7ZxArrVvFqOw+t+3RYZj/ts3AP9 Generated-by-Nova"

my_groups: "{{ instance_groups | selectattr('members', 'contains', inventory_hostname) }}"
is_main_instance: "{{ host_index == 100 }}"
main_instance_group: "{{ is_main_instance | ternary(my_groups | list | first, []) }}"
